# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GEOL_QMAPS
                                 A QGIS plugin
 GEOL_QMAPS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-13
        copyright            : (C) 2024 by GEOL_QMAPS
        email                : GEOL_QMAPS
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GEOL_QMAPS class from file GEOL_QMAPS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # NOTE: this used to call a _check_dependencies() helper here that shelled
    # out to `sys.executable -m pip install --upgrade ...` on the main thread
    # whenever scipy was below an overly strict floor. On QGIS's bundled
    # Python, sys.executable is the QGIS executable itself, not a plain
    # python.exe, so that command launched a second QGIS instance and hung
    # the first one waiting on it (no timeout, main thread). The plugin does
    # not actually need a recent scipy (see requirements.txt), so the check
    # and the auto-upgrade have been removed rather than fixed in place.
    from .GEOL_QMAPS import GEOL_QMAPS
    return GEOL_QMAPS(iface)
