# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WAXI_QF
                                 A QGIS plugin
 Supoprt QField usage by WAXI Team
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-31
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Mark Jessell UWA
        email                : mark.jessell@uwa.edu.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import Qgis, QgsProject, QgsVectorLayer
import pandas as pd

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .WAXI_QF_dialog import WAXI_QFDialog
import os.path


class WAXI_QF:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'WAXI_QF_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&WAXI_QF')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('WAXI_QF', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/WAXI_QF/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'WAXI QF'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def rmvLyr(lyrname):
        qinst = QgsProject.instance()
        qinst.removeMapLayer(qinst.mapLayersByName(lyrname)[0].id())

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&WAXI_QF'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = WAXI_QFDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            username = self.dlg.lineEdit.text()
            description = self.dlg.lineEdit_2.text()
            self.iface.messageBar().pushMessage("new user "+username, level=Qgis.Warning, duration=15)
            layer_name='User list'
            project = QgsProject.instance()
            layer = project.mapLayersByName(layer_name)
            group = QgsProject.instance().layerTreeRoot()
            print("group=",group)
            if len(layer) > 0:
                # Remove the layer from the project
                for layer in project.mapLayers().values():
                    # Check if the layer name matches the target name
                    if layer.name() == layer_name:
                        # Get the file path of the layer
                        file_path = layer.dataProvider().dataSourceUri()
                        print("File path:", file_path)
                        import pandas as pd
                        QgsProject.instance().removeMapLayer(layer)
                        User_List= pd.read_csv(file_path,encoding="latin_1",sep=";")
                        User_List.loc[str(len(User_List))] = [username,description]
                        User_List.to_csv(file_path,index=False,sep=";",encoding="latin_1")
                        updated_layer = QgsVectorLayer(file_path, layer_name, "ogr")
                        if updated_layer.isValid():
                            # Remove the existing layer from the project

                            # Add the updated layer to the project
                            QgsProject.instance().addMapLayer(updated_layer,False)
                            group = QgsProject.instance().layerTreeRoot().findGroup("CSV FILES")
                            if group:
                                # Remove the layer from its current group
                                #QgsProject.instance().layerTreeRoot().removeLayer(updated_layer)

                                # Add the layer to the new group
                                group.addLayer(updated_layer)

                                # Refresh the layer tree to reflect the changes
                                #node = QgsProject.instance().layerTreeRoot().findLayer(self.myLayer.id())
                                #self.iface.layerTreeView().layerTreeModel().refreshLayerLegend(node)                            print("Layer updated successfully.")
                        else:
                            print("Failed to load the updated layer.")
                        break  # Stop iterating once the layer is found
            else:
                self.iface.messageBar().pushMessage("Layer Failed to Delete: "+layer_name, level=Qgis.Warning, duration=15)
